services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/mysql
    ports:
      - 3333:3306
  
  php:
    build:
      context: ./docker/php
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./apache/limits.conf:/etc/apache2/conf-enabled/limits.conf:ro
      - ./apache/servername.conf:/etc/apache2/conf-enabled/servername.conf:ro
      - ./apache/app.conf:/etc/apache2/conf-enabled/app.conf:ro
    ports:
      - 8088:80
    depends_on:
      db:
        condition: service_started
    command: >
      bash -c "
        echo 'Exécution du script d''initialisation...' &&
        php /var/www/html/docker-init-db.php &&
        echo 'Démarrage d''Apache...' &&
        apache2-foreground
      "
  
  adminer:
    image: adminer:latest
    ports:
      - 8089:8080
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db:
