-- Inserts pour la table enigmes
-- 6 equipes x 3 jours = 18 enigmes

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

INSERT INTO `enigmes` (id_group, id_day, enigm_label, enigm_solution, status, solved) 
SELECT id_group, id_day, enigm_label, enigm_solution, status, solved FROM (
SELECT 1 as id_group, 1 as id_day, 'On y passe souvent en debut de journee, parfois seul, parfois a deux, rarement plus. C''est un lieu de transition, ni tout a fait detente, ni tout a fait travail. Certains y prennent un cafe en silence, d''autres y attendent sans vraiment attendre. Elle est proche sans etre centrale, pratique sans etre confortable. Personne ne s''y installe longtemps, mais tout le monde y passe. Le jour du hack, ce lieu n''etait pas vide. C''est la qu''un mouvement a ete trop rapide, ou trop bien calcule. Un geste banal, a une heure banal, dans un endroit banal. Et pourtant, c''est la que tout a commence.' as enigm_label, 'steve jobs' as enigm_solution, 0 as status, FALSE as solved
UNION ALL SELECT 2, 1, 'On y passe souvent en debut de journee, parfois seul, parfois a deux, rarement plus. C''est un lieu de transition, ni tout a fait detente, ni tout a fait travail. Certains y prennent un cafe en silence, d''autres y attendent sans vraiment attendre. Elle est proche sans etre centrale, pratique sans etre confortable. Personne ne s''y installe longtemps, mais tout le monde y passe. Le jour du hack, ce lieu n''etait pas vide. C''est la qu''un mouvement a ete trop rapide, ou trop bien calcule. Un geste banal, a une heure banal, dans un endroit banal. Et pourtant, c''est la que tout a commence.', 'steve jobs', 0, FALSE
UNION ALL SELECT 3, 1, 'On y passe souvent en debut de journee, parfois seul, parfois a deux, rarement plus. C''est un lieu de transition, ni tout a fait detente, ni tout a fait travail. Certains y prennent un cafe en silence, d''autres y attendent sans vraiment attendre. Elle est proche sans etre centrale, pratique sans etre confortable. Personne ne s''y installe longtemps, mais tout le monde y passe. Le jour du hack, ce lieu n''etait pas vide. C''est la qu''un mouvement a ete trop rapide, ou trop bien calcule. Un geste banal, a une heure banal, dans un endroit banal. Et pourtant, c''est la que tout a commence.', 'steve jobs', 0, FALSE
UNION ALL SELECT 4, 1, 'On y passe souvent en debut de journee, parfois seul, parfois a deux, rarement plus. C''est un lieu de transition, ni tout a fait detente, ni tout a fait travail. Certains y prennent un cafe en silence, d''autres y attendent sans vraiment attendre. Elle est proche sans etre centrale, pratique sans etre confortable. Personne ne s''y installe longtemps, mais tout le monde y passe. Le jour du hack, ce lieu n''etait pas vide. C''est la qu''un mouvement a ete trop rapide, ou trop bien calcule. Un geste banal, a une heure banal, dans un endroit banal. Et pourtant, c''est la que tout a commence.', 'steve jobs', 0, FALSE
UNION ALL SELECT 5, 1, 'On y passe souvent en debut de journee, parfois seul, parfois a deux, rarement plus. C''est un lieu de transition, ni tout a fait detente, ni tout a fait travail. Certains y prennent un cafe en silence, d''autres y attendent sans vraiment attendre. Elle est proche sans etre centrale, pratique sans etre confortable. Personne ne s''y installe longtemps, mais tout le monde y passe. Le jour du hack, ce lieu n''etait pas vide. C''est la qu''un mouvement a ete trop rapide, ou trop bien calcule. Un geste banal, a une heure banal, dans un endroit banal. Et pourtant, c''est la que tout a commence.', 'steve jobs', 0, FALSE
UNION ALL SELECT 6, 1, 'On y passe souvent en debut de journee, parfois seul, parfois a deux, rarement plus. C''est un lieu de transition, ni tout a fait detente, ni tout a fait travail. Certains y prennent un cafe en silence, d''autres y attendent sans vraiment attendre. Elle est proche sans etre centrale, pratique sans etre confortable. Personne ne s''y installe longtemps, mais tout le monde y passe. Le jour du hack, ce lieu n''etait pas vide. C''est la qu''un mouvement a ete trop rapide, ou trop bien calcule. Un geste banal, a une heure banal, dans un endroit banal. Et pourtant, c''est la que tout a commence.', 'steve jobs', 0, FALSE
UNION ALL SELECT 1, 2, 'Il n''a pas fait de bruit en entrant. Il n''a ni grince, ni sonne, ni vibre. Il s''est simplement glisse la ou l''on branche sans reflechir, comme un geste parmi tant d''autres dans une journee trop rapide. Il ne depend pas du reseau, et pourtant, il l''a contamine. Il n''a pas frappe, il s''est transmis. Son apparence est anodine, sa presence souvent oubliee, mais son contenu, lui, portait en germe la tempete. On l''a insere sans y penser, peut-etre pendant un appel, une relance, un moment de flottement. Et dans le ventre calme de la machine, il a commence a ecrire ce que personne ne voulait lire. Il n''a pas casse de porte, il a ouvert une faille. Et c''est la que tout a commence a tomber, doucement, mais irremediablement.', 'cle usb', 0, FALSE
UNION ALL SELECT 2, 2, 'Il n''a pas fait de bruit en entrant. Il n''a ni grince, ni sonne, ni vibre. Il s''est simplement glisse la ou l''on branche sans reflechir, comme un geste parmi tant d''autres dans une journee trop rapide. Il ne depend pas du reseau, et pourtant, il l''a contamine. Il n''a pas frappe, il s''est transmis. Son apparence est anodine, sa presence souvent oubliee, mais son contenu, lui, portait en germe la tempete. On l''a insere sans y penser, peut-etre pendant un appel, une relance, un moment de flottement. Et dans le ventre calme de la machine, il a commence a ecrire ce que personne ne voulait lire. Il n''a pas casse de porte, il a ouvert une faille. Et c''est la que tout a commence a tomber, doucement, mais irremediablement.', 'cle usb', 0, FALSE
UNION ALL SELECT 3, 2, 'Il n''a pas fait de bruit en entrant. Il n''a ni grince, ni sonne, ni vibre. Il s''est simplement glisse la ou l''on branche sans reflechir, comme un geste parmi tant d''autres dans une journee trop rapide. Il ne depend pas du reseau, et pourtant, il l''a contamine. Il n''a pas frappe, il s''est transmis. Son apparence est anodine, sa presence souvent oubliee, mais son contenu, lui, portait en germe la tempete. On l''a insere sans y penser, peut-etre pendant un appel, une relance, un moment de flottement. Et dans le ventre calme de la machine, il a commence a ecrire ce que personne ne voulait lire. Il n''a pas casse de porte, il a ouvert une faille. Et c''est la que tout a commence a tomber, doucement, mais irremediablement.', 'cle usb', 0, FALSE
UNION ALL SELECT 4, 2, 'Il n''a pas fait de bruit en entrant. Il n''a ni grince, ni sonne, ni vibre. Il s''est simplement glisse la ou l''on branche sans reflechir, comme un geste parmi tant d''autres dans une journee trop rapide. Il ne depend pas du reseau, et pourtant, il l''a contamine. Il n''a pas frappe, il s''est transmis. Son apparence est anodine, sa presence souvent oubliee, mais son contenu, lui, portait en germe la tempete. On l''a insere sans y penser, peut-etre pendant un appel, une relance, un moment de flottement. Et dans le ventre calme de la machine, il a commence a ecrire ce que personne ne voulait lire. Il n''a pas casse de porte, il a ouvert une faille. Et c''est la que tout a commence a tomber, doucement, mais irremediablement.', 'cle usb', 0, FALSE
UNION ALL SELECT 5, 2, 'Il n''a pas fait de bruit en entrant. Il n''a ni grince, ni sonne, ni vibre. Il s''est simplement glisse la ou l''on branche sans reflechir, comme un geste parmi tant d''autres dans une journee trop rapide. Il ne depend pas du reseau, et pourtant, il l''a contamine. Il n''a pas frappe, il s''est transmis. Son apparence est anodine, sa presence souvent oubliee, mais son contenu, lui, portait en germe la tempete. On l''a insere sans y penser, peut-etre pendant un appel, une relance, un moment de flottement. Et dans le ventre calme de la machine, il a commence a ecrire ce que personne ne voulait lire. Il n''a pas casse de porte, il a ouvert une faille. Et c''est la que tout a commence a tomber, doucement, mais irremediablement.', 'cle usb', 0, FALSE
UNION ALL SELECT 6, 2, 'Il n''a pas fait de bruit en entrant. Il n''a ni grince, ni sonne, ni vibre. Il s''est simplement glisse la ou l''on branche sans reflechir, comme un geste parmi tant d''autres dans une journee trop rapide. Il ne depend pas du reseau, et pourtant, il l''a contamine. Il n''a pas frappe, il s''est transmis. Son apparence est anodine, sa presence souvent oubliee, mais son contenu, lui, portait en germe la tempete. On l''a insere sans y penser, peut-etre pendant un appel, une relance, un moment de flottement. Et dans le ventre calme de la machine, il a commence a ecrire ce que personne ne voulait lire. Il n''a pas casse de porte, il a ouvert une faille. Et c''est la que tout a commence a tomber, doucement, mais irremediablement.', 'cle usb', 0, FALSE
UNION ALL SELECT 1, 3, 'Le hackeur intrigue autant qu''il echappe. Il parle peu, mais on retient ses silences. Il a les cheveux sombres, le regard souvent ailleurs, comme s''il vivait a moitie dans un autre fuseau horaire. On le voit parfois s''assoupir quelques minutes, toujours au meme endroit, entre deux reunions, ou au coeur du vacarme. Il observe plus qu''il ne mise, et ne revele jamais son jeu avant la derniere seconde. En recollant tout ca, un prenom finit par apparaitre, discret mais familier, comme une evidence que personne n''avait remarque avant.', 'yannick', 0, FALSE
UNION ALL SELECT 2, 3, 'Le hackeur intrigue autant qu''il echappe. Il parle peu, mais on retient ses silences. Il a les cheveux sombres, le regard souvent ailleurs, comme s''il vivait a moitie dans un autre fuseau horaire. On le voit parfois s''assoupir quelques minutes, toujours au meme endroit, entre deux reunions, ou au coeur du vacarme. Il observe plus qu''il ne mise, et ne revele jamais son jeu avant la derniere seconde. En recollant tout ca, un prenom finit par apparaitre, discret mais familier, comme une evidence que personne n''avait remarque avant.', 'yannick', 0, FALSE
UNION ALL SELECT 3, 3, 'Le hackeur intrigue autant qu''il echappe. Il parle peu, mais on retient ses silences. Il a les cheveux sombres, le regard souvent ailleurs, comme s''il vivait a moitie dans un autre fuseau horaire. On le voit parfois s''assoupir quelques minutes, toujours au meme endroit, entre deux reunions, ou au coeur du vacarme. Il observe plus qu''il ne mise, et ne revele jamais son jeu avant la derniere seconde. En recollant tout ca, un prenom finit par apparaitre, discret mais familier, comme une evidence que personne n''avait remarque avant.', 'yannick', 0, FALSE
UNION ALL SELECT 4, 3, 'Le hackeur intrigue autant qu''il echappe. Il parle peu, mais on retient ses silences. Il a les cheveux sombres, le regard souvent ailleurs, comme s''il vivait a moitie dans un autre fuseau horaire. On le voit parfois s''assoupir quelques minutes, toujours au meme endroit, entre deux reunions, ou au coeur du vacarme. Il observe plus qu''il ne mise, et ne revele jamais son jeu avant la derniere seconde. En recollant tout ca, un prenom finit par apparaitre, discret mais familier, comme une evidence que personne n''avait remarque avant.', 'yannick', 0, FALSE
UNION ALL SELECT 5, 3, 'Le hackeur intrigue autant qu''il echappe. Il parle peu, mais on retient ses silences. Il a les cheveux sombres, le regard souvent ailleurs, comme s''il vivait a moitie dans un autre fuseau horaire. On le voit parfois s''assoupir quelques minutes, toujours au meme endroit, entre deux reunions, ou au coeur du vacarme. Il observe plus qu''il ne mise, et ne revele jamais son jeu avant la derniere seconde. En recollant tout ca, un prenom finit par apparaitre, discret mais familier, comme une evidence que personne n''avait remarque avant.', 'yannick', 0, FALSE
UNION ALL SELECT 6, 3, 'Le hackeur intrigue autant qu''il echappe. Il parle peu, mais on retient ses silences. Il a les cheveux sombres, le regard souvent ailleurs, comme s''il vivait a moitie dans un autre fuseau horaire. On le voit parfois s''assoupir quelques minutes, toujours au meme endroit, entre deux reunions, ou au coeur du vacarme. Il observe plus qu''il ne mise, et ne revele jamais son jeu avant la derniere seconde. En recollant tout ca, un prenom finit par apparaitre, discret mais familier, comme une evidence que personne n''avait remarque avant.', 'yannick', 0, FALSE
) as enigmes_data
ON DUPLICATE KEY UPDATE 
    enigm_label = VALUES(enigm_label),
    enigm_solution = VALUES(enigm_solution),
    status = VALUES(status),
    solved = VALUES(solved),
    updated_at = CURRENT_TIMESTAMP;